FROM docker.io/searxng/searxng:latest

COPY searxng/settings.yml /etc/searxng/settings.yml

ENV SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml \
    SEARXNG_BIND_ADDRESS=0.0.0.0 \
    SEARXNG_PORT=10000 \
    SEARXNG_LIMITER=false \
    SEARXNG_PUBLIC_INSTANCE=false \
    SEARXNG_IMAGE_PROXY=false

EXPOSE 10000
