services:
  - type: web
    name: rozhan-searxng
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.searxng
    dockerContext: .
    region: oregon
    healthCheckPath: /healthz
    envVars:
      - key: SEARXNG_SECRET
        generateValue: true
      - key: SEARXNG_BIND_ADDRESS
        value: "0.0.0.0"
      - key: SEARXNG_LIMITER
        value: "false"
      - key: SEARXNG_PUBLIC_INSTANCE
        value: "false"
      - key: SEARXNG_IMAGE_PROXY
        value: "false"
